apiVersion: v1
kind: Service
metadata:
  name: sounio-stroke-api
  namespace: darwin-genomics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sounio-stroke-lab
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
