apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - runtime-config.yaml
  - rbac.yaml
  - dataset-pvc.yaml
  - kueue.yaml
  - api-deployment.yaml
  - api-service.yaml
