//! C-Compatible Autodiff Runtime Functions
//!
//! This module provides C-compatible Rust functions for automatic differentiation
//! that can be called from assembly code generated by the native backend.
//!
//! Supports both forward-mode (dual numbers) and reverse-mode (tape-based) autodiff.

use std::ffi::c_void;

/// Dual number structure (value, derivative)
/// Layout: [value: f64, derivative: f64]
#[repr(C)]
pub struct Dual {
    pub value: f64,
    pub derivative: f64,
}

impl Dual {
    pub fn new(value: f64, derivative: f64) -> Self {
        Self { value, derivative }
    }

    pub fn constant(value: f64) -> Self {
        Self {
            value,
            derivative: 0.0,
        }
    }

    pub fn variable(value: f64) -> Self {
        Self {
            value,
            derivative: 1.0,
        }
    }
}

/// Forward-mode autodiff: dual number addition
/// C signature: void sounio_dual_add(Dual* a, Dual* b, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_add(a: *const Dual, b: *const Dual, result: *mut Dual) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_der = (*a).derivative;
        let b_val = (*b).value;
        let b_der = (*b).derivative;

        (*result).value = a_val + b_val;
        (*result).derivative = a_der + b_der;
    }
}

/// Forward-mode autodiff: dual number subtraction
/// C signature: void sounio_dual_sub(Dual* a, Dual* b, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_sub(a: *const Dual, b: *const Dual, result: *mut Dual) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_der = (*a).derivative;
        let b_val = (*b).value;
        let b_der = (*b).derivative;

        (*result).value = a_val - b_val;
        (*result).derivative = a_der - b_der;
    }
}

/// Forward-mode autodiff: dual number multiplication (product rule)
/// C signature: void sounio_dual_mul(Dual* a, Dual* b, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_mul(a: *const Dual, b: *const Dual, result: *mut Dual) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_der = (*a).derivative;
        let b_val = (*b).value;
        let b_der = (*b).derivative;

        // Product rule: (a * b)' = a' * b + a * b'
        (*result).value = a_val * b_val;
        (*result).derivative = a_der * b_val + a_val * b_der;
    }
}

/// Forward-mode autodiff: dual number division (quotient rule)
/// C signature: void sounio_dual_div(Dual* a, Dual* b, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_div(a: *const Dual, b: *const Dual, result: *mut Dual) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_der = (*a).derivative;
        let b_val = (*b).value;
        let b_der = (*b).derivative;

        if b_val == 0.0 {
            // Division by zero - set result to NaN
            (*result).value = f64::NAN;
            (*result).derivative = f64::NAN;
            return;
        }

        // Quotient rule: (a / b)' = (a' * b - a * b') / b²
        (*result).value = a_val / b_val;
        let b_squared = b_val * b_val;
        (*result).derivative = (a_der * b_val - a_val * b_der) / b_squared;
    }
}

/// Forward-mode autodiff: compute gradient of scalar function
/// C signature: double sounio_autodiff_forward(
///     void (*f)(double*, double*),  // Function: f(x) -> y
///     double x,                      // Input value
///     double* gradient              // Output: df/dx at x
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_autodiff_forward(
    f: unsafe extern "C" fn(*const f64, *mut f64),
    x: f64,
    gradient: *mut f64,
) -> f64 {
    if gradient.is_null() {
        return f64::NAN;
    }

    // Simplified: compute numerical derivative as fallback
    // In production, this would use dual numbers directly
    let h = 1e-8;
    let mut y1 = 0.0;
    let mut y2 = 0.0;
    let x1 = x - h;
    let x2 = x + h;

    unsafe {
        f(&x1, &mut y1);
        f(&x2, &mut y2);
    }

    let result = (y2 - y1) / (2.0 * h);
    unsafe {
        *gradient = result;
    }

    // Return function value at x
    let mut y = 0.0;
    unsafe {
        f(&x, &mut y);
    }
    y
}

/// Reverse-mode autodiff: tape-based backpropagation
/// C signature: void sounio_autodiff_reverse(
///     void* tape,                   // Computation tape
///     double output_gradient,       // Gradient w.r.t. output
///     double* input_gradients,      // Output: gradients w.r.t. inputs
///     int n_inputs                  // Number of inputs
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_autodiff_reverse(
    _tape: *mut c_void,
    _output_gradient: f64,
    _input_gradients: *mut f64,
    _n_inputs: i32,
) {
    // TODO: Implement tape-based reverse mode autodiff
    // This requires:
    // 1. Tape structure to store computation graph
    // 2. Forward pass to build tape
    // 3. Backward pass to propagate gradients
    // For now, this is a placeholder
}

/// Forward-mode autodiff: dual number exponential
/// C signature: void sounio_dual_exp(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_exp(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        let exp_val = x_val.exp();
        // d/dx(exp(x)) = exp(x) * x'
        (*result).value = exp_val;
        (*result).derivative = exp_val * x_der;
    }
}

/// Forward-mode autodiff: dual number logarithm
/// C signature: void sounio_dual_log(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_log(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        if x_val <= 0.0 {
            (*result).value = f64::NAN;
            (*result).derivative = f64::NAN;
            return;
        }

        // d/dx(ln(x)) = x' / x
        (*result).value = x_val.ln();
        (*result).derivative = x_der / x_val;
    }
}

/// Forward-mode autodiff: dual number sine
/// C signature: void sounio_dual_sin(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_sin(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        // d/dx(sin(x)) = cos(x) * x'
        (*result).value = x_val.sin();
        (*result).derivative = x_val.cos() * x_der;
    }
}

/// Forward-mode autodiff: dual number cosine
/// C signature: void sounio_dual_cos(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_cos(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        // d/dx(cos(x)) = -sin(x) * x'
        (*result).value = x_val.cos();
        (*result).derivative = -x_val.sin() * x_der;
    }
}

/// Forward-mode autodiff: dual number power (x^p where p is constant)
/// C signature: void sounio_dual_pow(Dual* x, double power, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_pow(x: *const Dual, power: f64, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        if x_val <= 0.0 && power != power.floor() {
            // Negative base with non-integer exponent
            (*result).value = f64::NAN;
            (*result).derivative = f64::NAN;
            return;
        }

        let pow_val = x_val.powf(power);
        // d/dx(x^p) = p * x^(p-1) * x'
        (*result).value = pow_val;
        (*result).derivative = power * x_val.powf(power - 1.0) * x_der;
    }
}

/// Forward-mode autodiff: dual number square root
/// C signature: void sounio_dual_sqrt(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_sqrt(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        if x_val < 0.0 {
            (*result).value = f64::NAN;
            (*result).derivative = f64::NAN;
            return;
        }

        let sqrt_val = x_val.sqrt();
        // d/dx(sqrt(x)) = x' / (2 * sqrt(x))
        (*result).value = sqrt_val;
        (*result).derivative = x_der / (2.0 * sqrt_val);
    }
}
