//! C-Compatible Tensor Runtime Functions
//!
//! This module provides C-compatible Rust functions for tensor operations
//! that can be called from assembly code generated by the native backend.
//!
//! Supports matrix multiplication, einsum, and reshape operations.

/// Matrix multiplication: C = A @ B
/// 
/// C signature: void sounio_tensor_matmul(
///     const double* A,    // RDI: M×K matrix (row-major)
///     const double* B,    // RSI: K×N matrix (row-major)
///     double* C,          // RDX: M×N output matrix (row-major)
///     int M,              // RCX: rows of A
///     int K,              // R8:  columns of A / rows of B
///     int N               // R9:  columns of B
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tensor_matmul(
    a: *const f64,
    b: *const f64,
    c: *mut f64,
    m: i32,
    k: i32,
    n: i32,
) {
    if a.is_null() || b.is_null() || c.is_null() || m <= 0 || k <= 0 || n <= 0 {
        return;
    }

    let m = m as usize;
    let k = k as usize;
    let n = n as usize;

    let a_slice = unsafe { std::slice::from_raw_parts(a, m * k) };
    let b_slice = unsafe { std::slice::from_raw_parts(b, k * n) };
    let c_slice = unsafe { std::slice::from_raw_parts_mut(c, m * n) };

    // Initialize output to zero
    for i in 0..(m * n) {
        c_slice[i] = 0.0;
    }

    // Standard matrix multiplication: C[i,j] = sum_l A[i,l] * B[l,j]
    for i in 0..m {
        for j in 0..n {
            let mut sum = 0.0;
            for l in 0..k {
                sum += a_slice[i * k + l] * b_slice[l * n + j];
            }
            c_slice[i * n + j] = sum;
        }
    }
}

/// Einsum (Einstein summation) operation
/// 
/// C signature: void sounio_tensor_einsum(
///     const char* notation,  // RDI: einsum notation string (e.g., "ij,jk->ik")
///     const double** inputs, // RSI: array of input tensor pointers
///     int* input_shapes,     // RDX: flattened array of input shapes
///     int num_inputs,        // RCX: number of input tensors
///     double* output,         // R8:  output tensor (pre-allocated)
///     int* output_shape,     // R9:  output shape array
///     int output_rank         // Stack: output rank
/// )
/// 
/// Note: This is a simplified version. Full einsum requires parsing the notation
/// and handling arbitrary tensor contractions. For now, we support common cases.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tensor_einsum(
    _notation: *const i8,
    _inputs: *const *const f64,
    _input_shapes: *const i32,
    _num_inputs: i32,
    _output: *mut f64,
    _output_shape: *const i32,
    _output_rank: i32,
) {
    // TODO: Implement full einsum parser and evaluator
    // For now, this is a placeholder
    // In production, would:
    // 1. Parse notation string
    // 2. Determine contraction indices
    // 3. Compute output shape
    // 4. Perform tensor contraction
}

/// Reshape tensor to new shape (must have same total elements)
/// 
/// C signature: void sounio_tensor_reshape(
///     const double* input,   // RDI: input tensor (row-major)
///     double* output,         // RSI: output tensor (pre-allocated)
///     int* input_shape,       // RDX: input shape array
///     int input_rank,         // RCX: input rank
///     int* output_shape,      // R8:  output shape array
///     int output_rank,        // R9:  output rank
///     int total_elements      // Stack: total elements (must match)
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tensor_reshape(
    input: *const f64,
    output: *mut f64,
    _input_shape: *const i32,
    _input_rank: i32,
    _output_shape: *const i32,
    _output_rank: i32,
    total_elements: i32,
) {
    if input.is_null() || output.is_null() || total_elements <= 0 {
        return;
    }

    let n = total_elements as usize;
    let input_slice = unsafe { std::slice::from_raw_parts(input, n) };
    let output_slice = unsafe { std::slice::from_raw_parts_mut(output, n) };

    // Reshape is just copying data (assuming row-major for both)
    output_slice.copy_from_slice(input_slice);
}

/// Transpose matrix: B = A^T
/// 
/// C signature: void sounio_tensor_transpose(
///     const double* A,    // RDI: M×N matrix (row-major)
///     double* B,           // RSI: N×M output matrix (row-major)
///     int M,               // RDX: rows of A
///     int N                // RCX: columns of A
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tensor_transpose(
    a: *const f64,
    b: *mut f64,
    m: i32,
    n: i32,
) {
    if a.is_null() || b.is_null() || m <= 0 || n <= 0 {
        return;
    }

    let m = m as usize;
    let n = n as usize;

    let a_slice = unsafe { std::slice::from_raw_parts(a, m * n) };
    let b_slice = unsafe { std::slice::from_raw_parts_mut(b, m * n) };

    // Transpose: B[j,i] = A[i,j]
    for i in 0..m {
        for j in 0..n {
            b_slice[j * m + i] = a_slice[i * n + j];
        }
    }
}

/// Element-wise addition: C = A + B (with broadcasting support)
/// 
/// C signature: void sounio_tensor_add(
///     const double* A,    // RDI: first tensor
///     const double* B,    // RSI: second tensor
///     double* C,          // RDX: output tensor
///     int n               // RCX: number of elements
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tensor_add(
    a: *const f64,
    b: *const f64,
    c: *mut f64,
    n: i32,
) {
    if a.is_null() || b.is_null() || c.is_null() || n <= 0 {
        return;
    }

    let n = n as usize;
    
    // Use SIMD for large arrays (process 2 doubles at a time with XMM registers)
    if n >= 2 {
        let simd_chunks = n / 2;
        let remainder = n % 2;
        
        // Process 2 doubles at a time using unaligned loads/stores
        for i in 0..simd_chunks {
            let idx = i * 2;
            unsafe {
                // Load 2 doubles from a and b
                let a_vec = std::ptr::read_unaligned(a.add(idx) as *const [f64; 2]);
                let b_vec = std::ptr::read_unaligned(b.add(idx) as *const [f64; 2]);
                // Add element-wise
                let result = [a_vec[0] + b_vec[0], a_vec[1] + b_vec[1]];
                // Store result
                std::ptr::write_unaligned(c.add(idx) as *mut [f64; 2], result);
            }
        }
        
        // Handle remainder (scalar)
        if remainder > 0 {
            let idx = simd_chunks * 2;
            unsafe {
                *c.add(idx) = *a.add(idx) + *b.add(idx);
            }
        }
    } else {
        // Scalar fallback for small arrays
        unsafe {
            *c = *a + *b;
        }
    }
}

/// Element-wise multiplication (Hadamard product): C = A * B
/// 
/// C signature: void sounio_tensor_mul(
///     const double* A,    // RDI: first tensor
///     const double* B,    // RSI: second tensor
///     double* C,          // RDX: output tensor
///     int n               // RCX: number of elements
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tensor_mul(
    a: *const f64,
    b: *const f64,
    c: *mut f64,
    n: i32,
) {
    if a.is_null() || b.is_null() || c.is_null() || n <= 0 {
        return;
    }

    let n = n as usize;
    
    // Use SIMD for large arrays (process 2 doubles at a time with XMM registers)
    if n >= 2 {
        let simd_chunks = n / 2;
        let remainder = n % 2;
        
        // Process 2 doubles at a time using unaligned loads/stores
        for i in 0..simd_chunks {
            let idx = i * 2;
            unsafe {
                // Load 2 doubles from a and b
                let a_vec = std::ptr::read_unaligned(a.add(idx) as *const [f64; 2]);
                let b_vec = std::ptr::read_unaligned(b.add(idx) as *const [f64; 2]);
                // Multiply element-wise
                let result = [a_vec[0] * b_vec[0], a_vec[1] * b_vec[1]];
                // Store result
                std::ptr::write_unaligned(c.add(idx) as *mut [f64; 2], result);
            }
        }
        
        // Handle remainder (scalar)
        if remainder > 0 {
            let idx = simd_chunks * 2;
            unsafe {
                *c.add(idx) = *a.add(idx) * *b.add(idx);
            }
        }
    } else {
        // Scalar fallback for small arrays
        unsafe {
            *c = *a * *b;
        }
    }
}

/// Scale tensor: B = alpha * A
/// 
/// C signature: void sounio_tensor_scale(
///     const double* A,    // RDI: input tensor
///     double alpha,       // XMM0: scaling factor
///     double* B,          // RSI: output tensor
///     int n               // RDX: number of elements
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tensor_scale(
    a: *const f64,
    alpha: f64,
    b: *mut f64,
    n: i32,
) {
    if a.is_null() || b.is_null() || n <= 0 {
        return;
    }

    let n = n as usize;
    
    // Use SIMD for large arrays (process 2 doubles at a time with XMM registers)
    if n >= 2 {
        let simd_chunks = n / 2;
        let remainder = n % 2;
        
        // Broadcast alpha to a 2-element array for SIMD
        let alpha_vec = [alpha, alpha];
        
        // Process 2 doubles at a time using unaligned loads/stores
        for i in 0..simd_chunks {
            let idx = i * 2;
            unsafe {
                // Load 2 doubles from a
                let a_vec = std::ptr::read_unaligned(a.add(idx) as *const [f64; 2]);
                // Multiply by alpha
                let result = [a_vec[0] * alpha_vec[0], a_vec[1] * alpha_vec[1]];
                // Store result
                std::ptr::write_unaligned(b.add(idx) as *mut [f64; 2], result);
            }
        }
        
        // Handle remainder (scalar)
        if remainder > 0 {
            let idx = simd_chunks * 2;
            unsafe {
                *b.add(idx) = *a.add(idx) * alpha;
            }
        }
    } else {
        // Scalar fallback for small arrays
        unsafe {
            *b = *a * alpha;
        }
    }
}

/// Matrix-vector multiplication: y = A @ x
/// 
/// C signature: void sounio_tensor_matvec(
///     const double* A,    // RDI: M×N matrix (row-major)
///     const double* x,    // RSI: N-element vector
///     double* y,          // RDX: M-element output vector
///     int M,              // RCX: rows of A
///     int N               // R8:  columns of A
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tensor_matvec(
    a: *const f64,
    x: *const f64,
    y: *mut f64,
    m: i32,
    n: i32,
) {
    if a.is_null() || x.is_null() || y.is_null() || m <= 0 || n <= 0 {
        return;
    }

    let m = m as usize;
    let n = n as usize;

    let a_slice = unsafe { std::slice::from_raw_parts(a, m * n) };
    let x_slice = unsafe { std::slice::from_raw_parts(x, n) };
    let y_slice = unsafe { std::slice::from_raw_parts_mut(y, m) };

    // y[i] = sum_j A[i,j] * x[j]
    for i in 0..m {
        let mut sum = 0.0;
        for j in 0..n {
            sum += a_slice[i * n + j] * x_slice[j];
        }
        y_slice[i] = sum;
    }
}
