//! C-Compatible Uncertainty Propagation Runtime Functions
//!
//! This module provides C-compatible Rust functions for uncertainty propagation
//! that can be called from assembly code generated by the native backend.
//!
//! Implements GUM (Guide to the Expression of Uncertainty in Measurement)
//! propagation rules for uncertain<T> types.

/// Uncertain value structure (value, uncertainty)
/// Layout: [value: f64, uncertainty: f64]
#[repr(C)]
pub struct Uncertain {
    pub value: f64,
    pub uncertainty: f64,
}

impl Uncertain {
    pub fn new(value: f64, uncertainty: f64) -> Self {
        Self { value, uncertainty }
    }

    pub fn constant(value: f64) -> Self {
        Self {
            value,
            uncertainty: 0.0,
        }
    }
}

/// Uncertainty propagation: addition
/// For independent variables: u²(a+b) = u²(a) + u²(b)
/// 
/// C signature: void sounio_uncertain_add(
///     const Uncertain* a,    // RDI: first uncertain value
///     const Uncertain* b,    // RSI: second uncertain value
///     Uncertain* result       // RDX: result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_add(
    a: *const Uncertain,
    b: *const Uncertain,
    result: *mut Uncertain,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_unc = (*a).uncertainty;
        let b_val = (*b).value;
        let b_unc = (*b).uncertainty;

        // Value: a + b
        (*result).value = a_val + b_val;

        // Uncertainty: sqrt(u²(a) + u²(b)) for independent variables
        (*result).uncertainty = (a_unc * a_unc + b_unc * b_unc).sqrt();
    }
}

/// Uncertainty propagation: subtraction
/// For independent variables: u²(a-b) = u²(a) + u²(b)
/// 
/// C signature: void sounio_uncertain_sub(
///     const Uncertain* a,
///     const Uncertain* b,
///     Uncertain* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_sub(
    a: *const Uncertain,
    b: *const Uncertain,
    result: *mut Uncertain,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_unc = (*a).uncertainty;
        let b_val = (*b).value;
        let b_unc = (*b).uncertainty;

        // Value: a - b
        (*result).value = a_val - b_val;

        // Uncertainty: sqrt(u²(a) + u²(b))
        (*result).uncertainty = (a_unc * a_unc + b_unc * b_unc).sqrt();
    }
}

/// Uncertainty propagation: multiplication
/// For independent variables: u²(a*b) = (a*b)² * (u²(a)/a² + u²(b)/b²)
/// 
/// C signature: void sounio_uncertain_mul(
///     const Uncertain* a,
///     const Uncertain* b,
///     Uncertain* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_mul(
    a: *const Uncertain,
    b: *const Uncertain,
    result: *mut Uncertain,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_unc = (*a).uncertainty;
        let b_val = (*b).value;
        let b_unc = (*b).uncertainty;

        // Value: a * b
        (*result).value = a_val * b_val;

        // Uncertainty: |a*b| * sqrt((u(a)/a)² + (u(b)/b)²)
        // Handle division by zero
        if a_val == 0.0 && b_val == 0.0 {
            (*result).uncertainty = 0.0;
        } else if a_val == 0.0 {
            (*result).uncertainty = a_unc * b_val.abs();
        } else if b_val == 0.0 {
            (*result).uncertainty = b_unc * a_val.abs();
        } else {
            let rel_unc_a = a_unc / a_val.abs();
            let rel_unc_b = b_unc / b_val.abs();
            (*result).uncertainty = (a_val * b_val).abs() * (rel_unc_a * rel_unc_a + rel_unc_b * rel_unc_b).sqrt();
        }
    }
}

/// Uncertainty propagation: division
/// For independent variables: u²(a/b) = (a/b)² * (u²(a)/a² + u²(b)/b²)
/// 
/// C signature: void sounio_uncertain_div(
///     const Uncertain* a,
///     const Uncertain* b,
///     Uncertain* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_div(
    a: *const Uncertain,
    b: *const Uncertain,
    result: *mut Uncertain,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_unc = (*a).uncertainty;
        let b_val = (*b).value;
        let b_unc = (*b).uncertainty;

        if b_val == 0.0 {
            (*result).value = f64::NAN;
            (*result).uncertainty = f64::NAN;
            return;
        }

        // Value: a / b
        (*result).value = a_val / b_val;

        // Uncertainty: |a/b| * sqrt((u(a)/a)² + (u(b)/b)²)
        if a_val == 0.0 {
            (*result).uncertainty = a_unc / b_val.abs();
        } else {
            let rel_unc_a = a_unc / a_val.abs();
            let rel_unc_b = b_unc / b_val.abs();
            (*result).uncertainty = (a_val / b_val).abs() * (rel_unc_a * rel_unc_a + rel_unc_b * rel_unc_b).sqrt();
        }
    }
}

/// Combine multiple uncertain measurements (weighted average)
/// Uses inverse-variance weighting: w_i = 1 / u²_i
/// 
/// C signature: void sounio_uncertain_combine(
///     const Uncertain* measurements,  // RDI: array of uncertain values
///     int n,                            // RSI: number of measurements
///     Uncertain* result                 // RDX: combined result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_combine(
    measurements: *const Uncertain,
    n: i32,
    result: *mut Uncertain,
) {
    if measurements.is_null() || result.is_null() || n <= 0 {
        return;
    }

    let n = n as usize;
    let meas_slice = unsafe { std::slice::from_raw_parts(measurements, n) };

    unsafe {
        // Compute weighted average: x_combined = sum(w_i * x_i) / sum(w_i)
        // where w_i = 1 / u²_i
        let mut sum_weighted = 0.0;
        let mut sum_weights = 0.0;

        for meas in meas_slice {
            if meas.uncertainty > 0.0 {
                let weight = 1.0 / (meas.uncertainty * meas.uncertainty);
                sum_weighted += weight * meas.value;
                sum_weights += weight;
            } else {
                // Zero uncertainty - exact value, use it directly
                (*result).value = meas.value;
                (*result).uncertainty = 0.0;
                return;
            }
        }

        if sum_weights > 0.0 {
            (*result).value = sum_weighted / sum_weights;
            // Combined uncertainty: u_combined = 1 / sqrt(sum(w_i))
            (*result).uncertainty = 1.0 / sum_weights.sqrt();
        } else {
            // All measurements have infinite uncertainty
            (*result).value = 0.0;
            (*result).uncertainty = f64::INFINITY;
        }
    }
}

/// Scale uncertain value: result = alpha * x
/// Uncertainty scales linearly: u(result) = |alpha| * u(x)
/// 
/// C signature: void sounio_uncertain_scale(
///     const Uncertain* x,    // RDI: input uncertain value
///     double alpha,           // XMM0: scaling factor
///     Uncertain* result        // RSI: result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_scale(
    x: *const Uncertain,
    alpha: f64,
    result: *mut Uncertain,
) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        (*result).value = (*x).value * alpha;
        (*result).uncertainty = (*x).uncertainty * alpha.abs();
    }
}

/// Power operation: result = x^p
/// Uncertainty: u(result) = |p * x^(p-1)| * u(x)
/// 
/// C signature: void sounio_uncertain_pow(
///     const Uncertain* x,    // RDI: base
///     double power,          // XMM0: exponent
///     Uncertain* result       // RSI: result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_pow(
    x: *const Uncertain,
    power: f64,
    result: *mut Uncertain,
) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_unc = (*x).uncertainty;

        if x_val <= 0.0 && power != power.floor() {
            // Negative base with non-integer exponent
            (*result).value = f64::NAN;
            (*result).uncertainty = f64::NAN;
            return;
        }

        // Value: x^p
        (*result).value = x_val.powf(power);

        // Uncertainty: |p * x^(p-1)| * u(x)
        if x_val == 0.0 {
            (*result).uncertainty = 0.0;
        } else {
            let deriv = power * x_val.powf(power - 1.0);
            (*result).uncertainty = deriv.abs() * x_unc;
        }
    }
}

/// Square root: result = sqrt(x)
/// Uncertainty: u(result) = u(x) / (2 * sqrt(x))
/// 
/// C signature: void sounio_uncertain_sqrt(
///     const Uncertain* x,
///     Uncertain* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_sqrt(
    x: *const Uncertain,
    result: *mut Uncertain,
) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_unc = (*x).uncertainty;

        if x_val < 0.0 {
            (*result).value = f64::NAN;
            (*result).uncertainty = f64::NAN;
            return;
        }

        let sqrt_val = x_val.sqrt();
        (*result).value = sqrt_val;

        // Uncertainty: u(sqrt(x)) = u(x) / (2 * sqrt(x))
        if sqrt_val > 0.0 {
            (*result).uncertainty = x_unc / (2.0 * sqrt_val);
        } else {
            (*result).uncertainty = 0.0;
        }
    }
}

/// Exponential: result = exp(x)
/// Uncertainty: u(result) = exp(x) * u(x)
/// 
/// C signature: void sounio_uncertain_exp(
///     const Uncertain* x,
///     Uncertain* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_exp(
    x: *const Uncertain,
    result: *mut Uncertain,
) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_unc = (*x).uncertainty;

        let exp_val = x_val.exp();
        (*result).value = exp_val;

        // Uncertainty: u(exp(x)) = exp(x) * u(x)
        (*result).uncertainty = exp_val * x_unc;
    }
}

/// Natural logarithm: result = ln(x)
/// Uncertainty: u(result) = u(x) / x
/// 
/// C signature: void sounio_uncertain_log(
///     const Uncertain* x,
///     Uncertain* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_uncertain_log(
    x: *const Uncertain,
    result: *mut Uncertain,
) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_unc = (*x).uncertainty;

        if x_val <= 0.0 {
            (*result).value = f64::NAN;
            (*result).uncertainty = f64::NAN;
            return;
        }

        (*result).value = x_val.ln();

        // Uncertainty: u(ln(x)) = u(x) / x
        (*result).uncertainty = x_unc / x_val;
    }
}
