apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder-workspace-provisioner
  namespace: workspace-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder-workspace-provisioner
  namespace: workspace-plane
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "persistentvolumeclaims", "services", "secrets", "configmaps"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-workspace-provisioner
  namespace: workspace-plane
subjects:
  - kind: ServiceAccount
    name: coder-control-plane
    namespace: coder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coder-workspace-provisioner
