#I "../fsharp/src/Darwin.ResearchOs.Api/bin/Debug/net8.0"
#r "Microsoft.Extensions.Logging.Abstractions.dll"
#r "Darwin.ResearchOs.Contracts.dll"
#r "Darwin.ResearchOs.Core.dll"
#r "Darwin.ResearchOs.Storage.dll"

open System
open System.Collections.Generic
open System.IO
open Darwin.ResearchOs.Contracts
open Darwin.ResearchOs.Core
open Darwin.ResearchOs.Storage

let connectionString =
    Environment.GetEnvironmentVariable("DARWIN_RESEARCH_OS_DB_URL")
    |> function
        | null | "" -> failwith "DARWIN_RESEARCH_OS_DB_URL is required"
        | value -> value

let objectRoot =
    Environment.GetEnvironmentVariable("DARWIN_RESEARCH_OS_OBJECT_ROOT")
    |> function
        | null | "" -> Path.Combine(Directory.GetCurrentDirectory(), ".rewrite-cache", "postgres-smoke")
        | value -> value

Directory.CreateDirectory(objectRoot) |> ignore

let dict (pairs: seq<string * obj>) =
    let target = Dictionary<string, obj>()
    for (key, value) in pairs do
        target[key] <- value
    target

let metric value = dict [ "value", box value ]

let now () = DateTime.UtcNow.ToString("O")
let smokeId = DateTime.UtcNow.ToString("yyyyMMddHHmmss")

let runId = $"rewrite-run-{smokeId}"
let jobId = $"rewrite-job-{smokeId}"
let campaignId = $"rewrite-campaign-{smokeId}"
let programId = $"rewrite-program-{smokeId}"
let artifactId = $"rewrite-artifact-{smokeId}"
let workerId = $"rewrite-worker-{smokeId}"

let store = PostgresResearchStore(connectionString)
store.Initialize()

let researchStore = store :> IResearchStore
let objectStore = FilesystemObjectStore(objectRoot) :> IObjectStore

let benchmarkRun =
    { Defaults.benchmarkRun runId "rewrite-postgres-smoke-v1" with
        JobId = Some jobId
        Metrics =
            dict
                [ "sounio_hypercomplex",
                  box (
                      dict
                          [ "isles_dice", box (metric 0.71)
                            "auc", box (metric 0.84)
                            "aspects_mae", box (metric 0.52) ]
                  ) ]
        Leaderboard =
            dict
                [ "overall_rank",
                  box (
                      ResizeArray(
                          [ dict [ "model_name", box "sounio_hypercomplex" ] ]
                      )
                  ) ] }

let benchmarkJob =
    { JobId = jobId
      CreatedAt = now ()
      UpdatedAt = now ()
      OwnerType = "benchmark_run"
      OwnerId = runId
      Kind = "benchmark"
      Status = "completed"
      QueueName = "rewrite-parity"
      Executor = "manual-smoke"
      RequestPayload = dict [ "dataset_manifest_path", box "/tmp/rewrite-manifest.json"; "seed", box 13 ]
      ResultPayload = dict [ "benchmark_run_id", box runId; "backend", box "fsharp-postgres-smoke" ]
      Error = "" }

let campaignEntry =
    { EntryId = $"rewrite-entry-{smokeId}"
      Label = "postgres-smoke-seed-13"
      Request = Defaults.benchmarkRequest "/tmp/rewrite-manifest.json"
      JobId = Some jobId
      Status = "completed"
      BenchmarkRunId = Some runId
      Error = "" }

let baseCampaign =
    { CampaignId = campaignId
      CreatedAt = now ()
      UpdatedAt = now ()
      Name = "Rewrite Postgres Smoke"
      Objective = "Validate the F# rewrite lane against a live Postgres state store."
      Kind = "benchmark"
      ProgramId = Some programId
      Status = "created"
      BenchmarkSpecs = ResizeArray([ campaignEntry ])
      Notes = "Generated by scripts/fsharp_postgres_smoke.fsx"
      Summary = Dictionary() }

let deps : CampaignSemantics.Dependencies =
    { TryGetJob = researchStore.TryGetJob
      TryGetBenchmarkRun = researchStore.TryGetBenchmarkRun }

let objectDescriptor =
    objectStore.WriteJson(
        $"campaigns/{campaignId}/summary.json",
        dict [ "campaign_id", box campaignId; "run_id", box runId; "status", box "completed" ]
    )

let artifact =
    { ArtifactId = artifactId
      CreatedAt = now ()
      OwnerType = "campaign"
      OwnerId = campaignId
      Name = "campaign_summary"
      Kind = "json"
      Path = objectDescriptor.LocalPath
      Uri = objectDescriptor.Uri
      Description = "Smoke artifact for the F# Postgres-backed rewrite lane."
      ContentType = defaultArg objectDescriptor.ContentType "application/json"
      Bytes =
          match objectDescriptor.Bytes with
          | Some value -> Nullable value
          | None -> Nullable() }

researchStore.SaveBenchmarkRun(benchmarkRun)
researchStore.SaveJob(benchmarkJob)
let reconciledCampaign = CampaignSemantics.reconcile deps baseCampaign
researchStore.SaveCampaign(reconciledCampaign)

let baseProgram =
    { ProgramId = programId
      CreatedAt = now ()
      UpdatedAt = now ()
      Name = "Rewrite Smoke Program"
      Objective = "Check that F# programs reconcile over Postgres-backed campaigns."
      Hypothesis = "The F# lane can read and aggregate a live benchmark campaign from Postgres."
      Notes = "Generated by scripts/fsharp_postgres_smoke.fsx"
      Status = "created"
      CampaignIds = ResizeArray([ campaignId ])
      Summary = Dictionary() }

let reconciledProgram = ProgramSemantics.reconcile [ reconciledCampaign ] baseProgram
researchStore.SaveProgram(reconciledProgram)
researchStore.SaveArtifact(artifact)

researchStore.SaveWorkerHeartbeat(
    { WorkerId = workerId
      WorkerKind = "benchmark"
      Backend = "postgres"
      Executor = "manual-smoke"
      Hostname = Environment.MachineName
      CreatedAt = now ()
      UpdatedAt = now ()
      Notes = "Smoke heartbeat from the F# rewrite lane." }
)

let campaignPortfolio = PortfolioSemantics.buildCampaignPortfolio (researchStore.ListCampaigns())
let programPortfolio = PortfolioSemantics.buildProgramPortfolio [ reconciledProgram ]

printfn "{"
printfn "  \"job_id\": \"%s\"," jobId
printfn "  \"run_id\": \"%s\"," runId
printfn "  \"campaign_id\": \"%s\"," campaignId
printfn "  \"program_id\": \"%s\"," programId
printfn "  \"artifact_id\": \"%s\"," artifactId
printfn "  \"campaign_leading_model\": \"%s\"," (defaultArg campaignPortfolio.Campaigns[0].LeadingModel "")
printfn "  \"program_leading_id\": \"%s\"," (defaultArg programPortfolio.LeadingProgramId "")
printfn "  \"object_path\": \"%s\"" objectDescriptor.LocalPath
printfn "}"
